Resources:
  AssetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "asset_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "asset_id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "assets"

  PortfoliosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "portfolios"

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "transaction_date"
          AttributeType: "S"
        - AttributeName: "asset_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
        - AttributeName: "transaction_date"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "transactions"
      GlobalSecondaryIndexes:
        - IndexName: "username-asset_id-index"
          KeySchema:
            - AttributeName: "username"
              KeyType: "HASH"
            - AttributeName: "asset_id"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "users"

  SettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "master_assets"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "master_assets"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "settings"