@startuml
title Get Portfolio's History
actor Client

participant "Portfolio Page" as portfolioPage
activate Client
activate GetPortfolioHistoryActivity
database DynamoDB

Client -> portfolioPage : visit the portfolio page
portfolioPage -> GetPortfolioHistoryActivity :  send get portfolio's History request
GetPortfolioHistoryActivity -> DynamoDB : load portfolio's Historical Data for the user
DynamoDB -> GetPortfolioHistoryActivity : portfolio's Historical Data from the DB
GetPortfolioHistoryActivity -> portfolioPage : portfolio's historical data result
portfolioPage -> Client : Historical data displayed to the user
deactivate Client
deactivate GetPortfolioHistoryActivity
@enduml
