@startuml
title Get Portfolios
actor Client

participant "Portfolio Page" as portfolioPage
activate Client
activate GetPortfolioActivity
database DynamoDB

Client -> portfolioPage : visit the portfolio page
portfolioPage -> GetPortfolioActivity :  send get portfolio request
GetPortfolioActivity -> DynamoDB : load portfolio
DynamoDB -> GetPortfolioActivity : portfolio item by userId
GetPortfolioActivity -> portfolioPage : List <PortfolioModel>
portfolioPage -> Client : Portfolio successfully displayed
deactivate Client
deactivate GetPortfolioActivity
@enduml