@startuml
title Login
actor Client

participant "Login Page" as loginPage
activate Client
activate loginPage
activate LoginActivity
database users

Client -> loginPage : submit login form
loginPage -> LoginActivity : send login request
LoginActivity -> users : verify user in users
deactivate Client
deactivate loginPage
deactivate LoginActivity
@enduml