@startuml
title Portfolio Tracker


Portfolio --* UpdatePortfolio
GetPortfolioHistory --* PortfolioHistory
GetPortfolioHistory --* ConsolidatedPortfolioHistory
GetPortfolio --* Portfolio
User --* CreatePortfolio
User --* GetPortfolio
Portfolio --* GetPortfolioHistory
GetAsset --* Asset
Asset --* AssetHistory
Portfolio --* GetAsset

class User {
  -@DynamoDBHashKey userName : String
  -password : String
}

class Asset {
  -@DynamoDBHashKey assetId : String
  -@DynamoDBRangeKey marketCap : Integer
  -assetName : String
  -assetImage : String
  -totalSupply : Integer
  -usdValue: Integer
  -isAvailable : bool
}

class Portfolio {
   -@DynamoDBDKey userId : String
   -userId : String
   -assetQuantity : Integer
}

class AssetHistory {
  -@DynamoDBDocument : Map
  -@DynamoDBBHashKey assetId : String
  -@DynamoDBRangeKey timeStamp : String
  -usdValue : Integer
}

class PortfolioHistory {
  -@DynamoDBDocument : Map
  -@DynamoDBBHashKey assetId : String
  -@DynamoDBRangeKey timeStamp : String
}

class ConsolidatedPortfolioHistory {
  -@DynamoDBBHashKey userId : String
  -@DynamoDBRangeKey timeStamp : String
  -totalUsdValue: Integer
}

class GetAsset {
}

class CreatePortfolio {
}

class GetPortfolio {
}

class UpdatePortfolio {
}

class GetPortfolioHistory {
}

@enduml